### ISSUE TITLE
Does this support the new Garmin LIDAR v4?

### ISSUE THREAD

**Issue by jeff-kissinger** [adafruit/Adafruit_CircuitPython_LIDARLite#11]
I get a response back as Measurement failure or System failure.  Has this been tested successfully on the v4 Garmin LIDAR?

**Comment by ladyada** [comment]
nope it has not been tested - probably does not work!

**Comment by jeff-kissinger** [comment]
Thank you for responding. I'll modify the LIDARLite class in this repository to try to get it working and do a pull request if I do.  I don't have the LIDAR version 3 but I'm comparing the specs to see what's different. My Garmin LIDAR v4 seems to be operational due to the red LED blinking inside and I've triple checked my wiring so it seems to be an issue with the code.

**Comment by dastels** [comment]
It does not work at all. The v4LED interface/registers-set is almost completely different. I've been working with oldblackcrow on the forums about this.  I just got a LidarLiteV4 and have been hacking on the library and have something that seems to work. The measurements aren't right (in terms of centimeters, but they vary somewhat proportionally to the distance. I'll eventually take my findings to add a new class to the library and do a PR.

**Comment by sivashankar28** [comment]
Is there any updates at all? I am trying to use my NVIDIA AGX and use it for the garmin lidarlite v4 and am getting measurement failure as well.

**Comment by philletourneau** [comment]
oh my god I've been banging my head against a wall for hours trying to make this work! Can anyone share some functional code yet?
