### ISSUE TITLE
NameError: name 'WriteableBuffer' is not defined (Lidar Lite V3)

### ISSUE THREAD

**Issue by MuhammadBilal1** [adafruit/Adafruit_CircuitPython_LIDARLite#16]
Hi,
I am getting an issue while trying to use the library "adafruit_circuitpython_lidarlite".

Below are the details of my environment:
**1-** Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**2-** Raspberry Pi 4 Model B
**3-** Germin Lidar Lite V3
**4-** SDA & SCL Ports

**I am getting this issue on both versions (1.2.6 & 1.2.7).**

**Error:**
Traceback (most recent call last):
  File "lidarlite.py", line 4, in <module>
    import adafruit_lidarlite
  File "/home/ubuntu/.local/lib/python3.6/site-packages/adafruit_lidarlite.py", line 30, in <module>
    from adafruit_bus_device.i2c_device import I2CDevice
  File "/usr/local/lib/python3.6/dist-packages/adafruit_bus_device/i2c_device.py", line 26, in <module>
    class I2CDevice:
  File "/usr/local/lib/python3.6/dist-packages/adafruit_bus_device/i2c_device.py", line 65, in I2CDevice
    self, buf: WriteableBuffer, *, start: int = 0, end: Optional[int] = None
NameError: name 'WriteableBuffer' is not defined

![image](https://user-images.githubusercontent.com/7131058/153836619-e5407b40-b669-440e-aa42-aa7455eca54e.png)

**Comment by FoamyGuy** [comment]
@MuhammadBilal1 can you post the results of running:
```
pip show Adafruit-Blinka
```
I think this error may have been recently fixed in that library (last few days). So if you are not on the absolute newest version go ahead and try updating to the newest.

**Comment by MuhammadBilal1** [comment]
This worked fine and now this issue isn't appearing.
But now I am getting a new issue. Creating a new ticket for that issue.
Thank you for the help.

**Comment by FoamyGuy** [comment]
closing this issue and moving to #17
