### ISSUE TITLE
NameError: name 'I2C' is not defined (Raspberry Pi 4 Model B - Ubuntu 18.04 - adafruit_lidarlite)

### ISSUE THREAD

**Issue by MuhammadBilal1** [adafruit/Adafruit_CircuitPython_LIDARLite#17]
I am getting an issue while trying to use the library "adafruit_circuitpython_lidarlite".

Below are the details of my environment:

**1-** Distributor ID: [Ubuntu](https://cdimage.ubuntu.com/releases/18.04/release/) (ubuntu-18.04.5-preinstalled-server-arm64+raspi4.img.xz)

----> Description: Ubuntu 18.04.6 LTS

----> Release: 18.04

----> Codename: bionic

**2-** Raspberry Pi 4 Model B Rev 1.4

**3-** [Germin Lidar Lite V3](https://www.garmin.com/en-US/p/557294)

**4-** SDA & SCL Ports

I am getting this issue on both versions (1.2.6 & 1.2.7).

Installed the lidarlite adafruite library with the below command:

`sudo pip3 install adafruit-circuitpython-lidarlite`

I enabled the I2C port from the `raspi-config` also, but I am still getting the same issue.

I am not sure, but [I read that this might be something with the Raspberry Pi 4 Model B Revisions](https://raspberrypi.stackexchange.com/questions/135603/i2c-not-detecting-on-raspberry-pi-4-model-b-rev-1-5#:%7E:text=The%20full%20setup%20works%20fine%20when%20swapping%20out%20the%20Pi%204%20for%20a%20Raspberry%20Pi%203%20Model%20B%20Rev%201.2.%20Thanks%20in%20advance!). 

I checked this on Revision 1.1 & Revision 1.4 of Raspberry 4 Model B. But about 2 weeks ago the same worked on one of my Raspberry Pi 4 Model B without giving me any errors. But now that Pi is dead I don't know why. 
**I changed the Pi and this problem started appearing.**

I tried the same on the NVidia Jetson and the problem is the same there too.

![image](https://user-images.githubusercontent.com/7131058/153892895-a6685422-a1bc-4ac2-bb19-c314290b7efe.png)

![image](https://user-images.githubusercontent.com/7131058/153892938-6d0fbcc4-a9bb-458e-a1ed-9ec3384fce4a.png)

**Comment by MuhammadBilal1** [comment]
@FoamyGuy  Can you please help me here?

**Comment by FoamyGuy** [comment]
@MuhammadBilal1 please post the results from:
```
pip show Adafruit-Blinka
```
I believe this is a manifestation of the same problem I mentioned before that was resolved within Adafruit-Blinka within the last few days. The above command will show us what version you have installed which will help to verify if this is the case.

**Comment by MuhammadBilal1** [comment]
> @MuhammadBilal1 please post the results from:
> 
> ```
> pip show Adafruit-Blinka
> ```
> 
> I believe this is a manifestation of the same problem I mentioned before that was resolved within Adafruit-Blinka within the last few days. The above command will show us what version you have installed which will help to verify if this is the case.

Here is the result of the said command.

![image](https://user-images.githubusercontent.com/7131058/153896211-c96f7566-256e-47c5-ba0d-f3da95f3a4ed.png)

**Comment by FoamyGuy** [comment]
Thank you. The latest release currently is `6.20.4` [releases](https://github.com/adafruit/Adafruit_Blinka/releases). I believe if you can get that version installed it should resolve the issues you're seeing.

However the next hurdle that may arise is I think Blinka now has dependency for python 3.7+ and you have 3.6.9 so my guess is that pip will not automatically get you the latest version. Are you able to try updating to python 3.7 or using a venv that is py3.7+?

**Comment by MuhammadBilal1** [comment]
> Thank you. The latest release currently is `6.20.4` [releases](https://github.com/adafruit/Adafruit_Blinka/releases). I believe if you can get that version installed it should resolve the issues you're seeing.
> 
> However the next hurdle that may arise is I think Blinka now has dependency for python 3.7+ and you have 3.6.9 so my guess is that pip will not automatically get you the latest version. Are you able to try updating to python 3.7 or using a venv that is py3.7+?

Let me update my python version then I will get back to you.
Thank you for your response.

**Comment by MuhammadBilal1** [comment]
> Thank you. The latest release currently is `6.20.4` [releases](https://github.com/adafruit/Adafruit_Blinka/releases). I believe if you can get that version installed it should resolve the issues you're seeing.
> 
> However the next hurdle that may arise is I think Blinka now has dependency for python 3.7+ and you have 3.6.9 so my guess is that pip will not automatically get you the latest version. Are you able to try updating to python 3.7 or using a venv that is py3.7+?

Thank you for your support.
I updated installed the newer version of python (3.8.5) on my Raspberry Pi and installed the **adafruit-blinka** & **adafruit-circuitpython-lidarlite** and this fixed my issue.

Issue resolved after updating python and installing the newer version of blinka.
