### ISSUE TITLE
Please update for LidarLiteV4

### ISSUE THREAD

**Issue by philletourneau** [adafruit/Adafruit_CircuitPython_LIDARLite#19]
Can you please update this library to support the new LidarLiteV4?

I spent over an hour trying to set it up with this library, as the library does not specifically specify that it doesn't work with this model, and it is a module that is sold on the Adafruit store.

Thanks!

**Comment by ladyada** [comment]
thanks! closing as duplicate of
https://github.com/adafruit/Adafruit_CircuitPython_LIDARLite/issues/14
