### ISSUE TITLE
pip3 install failing

### ISSUE THREAD

**Issue by SpencerHehl** [adafruit/Adafruit_CircuitPython_LIDARLite#4]
invalid py_module declaration in setup.py currently references 'adafruit_bmp280' rather than its own adafruit_lidarlite module. once "installed" the module doesnt exist in the dist-packages and cannot be imported/used.

**Comment by ladyada** [comment]
@dastels plzfix!

**Comment by caternuson** [comment]
@SpencerHehl Please try the 1.1.2 version of the library when it becomes available.

**Comment by evaherrada** [comment]
I just tested and it installed fine

Edit: @SpencerHehl If you're still having issues, reopen this.
