### ISSUE TITLE
python module error

### ISSUE THREAD

**Issue by pslade2** [adafruit/Adafruit_CircuitPython_LIDARLite#6]
Hi, the install works fine for me but when I try to run the example it is not able to import adafruit_lidarlite resulting in the error:
ModuleNotFoundError: No module named 'adafruit_lidarlite'

Is this related to the other issue of improper install setup? Thanks.

**Comment by caternuson** [comment]
Probably related. Please try the 1.1.2 version of the library when it becomes available.

**Comment by kattni** [comment]
@pslade2 Please try the new version of the lib if you get a chance. Thanks!

**Comment by evaherrada** [comment]
@pslade2 I tested this by just importing it and doing nothing else (I don't have the right hardware but simply importing it doesn't require any) and it worked fine. Reopen this if you're still having issues
